apps/block_scout_web/lib/block_scout_web/admin_router.ex
defmodule BlockScoutWeb.AdminRouter do
  @moduledoc """
  Router for admin pages.
  """

  use BlockScoutWeb, :router

  alias BlockScoutWeb.Plug.FetchUserFromSession
  alias BlockScoutWeb.Plug.Admin.{CheckOwnerRegistered, RequireAdminRole}

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(BlockScoutWeb.CSPHeader)
  end

  pipeline :check_configured do
    plug(CheckOwnerRegistered)
  end

  pipeline :ensure_admin do
    plug(FetchUserFromSession)
    plug(RequireAdminRole)
  end

  scope "/setup", BlockScoutWeb.Admin do
    pipe_through([:browser])

    get("/", SetupController, :configure)
    post("/", SetupController, :configure_admin)
  end

  scope "/login", BlockScoutWeb.Admin do
    pipe_through([:browser, :check_configured])

    get("/", SessionController, :new)
    post("/", SessionController, :create)
  end

  scope "/", BlockScoutWeb.Admin do
    pipe_through([:browser, :check_configured, :ensure_admin])

    get("/", DashboardController, :index)
  end
end

apps/block_scout_web/lib/block_scout_web/router.ex
defmodule BlockScoutWeb.Router do
  use BlockScoutWeb, :router

  alias BlockScoutWeb.Plug.GraphQL

  forward("/wobserver", Wobserver.Web.Router)
  forward("/admin", BlockScoutWeb.AdminRouter)

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(BlockScoutWeb.CSPHeader)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/api/v1", BlockScoutWeb.API.V1, as: :api_v1 do
    pipe_through(:api)

    get("/supply", SupplyController, :supply)
  end

  scope "/api", BlockScoutWeb.API.RPC do
    pipe_through(:api)

    alias BlockScoutWeb.API.RPC

    forward("/", RPCTranslator, %{
      "block" => RPC.BlockController,
      "account" => RPC.AddressController,
      "logs" => RPC.LogsController,
      "token" => RPC.TokenController,
      "stats" => RPC.StatsController,
      "contract" => RPC.ContractController,
      "transaction" => RPC.TransactionController
    })
  end

  # Needs to be 200 to support the schema introspection for graphiql
  @max_complexity 200

  forward("/graphql", Absinthe.Plug,
    schema: BlockScoutWeb.Schema,
    analyze_complexity: true,
    max_complexity: @max_complexity
  )

  forward("/graphiql", Absinthe.Plug.GraphiQL,
    schema: BlockScoutWeb.Schema,
    interface: :advanced,
    default_query: GraphQL.default_query(),
    socket: BlockScoutWeb.UserSocket,
    analyze_complexity: true,
    max_complexity: @max_complexity
  )

  # Disallows Iframes (write routes)
  scope "/", BlockScoutWeb do
    pipe_through(:browser)
  end

  # Allows Iframes (read-only routes)
  scope "/", BlockScoutWeb do
    pipe_through([:browser, BlockScoutWeb.Plug.AllowIframe])

    resources("/", ChainController, only: [:show], singleton: true, as: :chain)

    resources("/market_history_chart", Chain.MarketHistoryChartController, only: [:show], singleton: true)

    resources "/blocks", BlockController, only: [:index, :show], param: "hash_or_number" do
      resources("/transactions", BlockTransactionController, only: [:index], as: :transaction)
    end

    get("/reorgs", BlockController, :reorg, as: :reorg)

    get("/uncles", BlockController, :uncle, as: :uncle)

    resources("/pending_transactions", PendingTransactionController, only: [:index])

    resources("/recent_transactions", RecentTransactionsController, only: [:index])

    get("/txs", TransactionController, :index)

    resources "/tx", TransactionController, only: [:show] do
      resources(
        "/internal_transactions",
        TransactionInternalTransactionController,
        only: [:index],
        as: :internal_transaction
      )

      resources("/logs", TransactionLogController, only: [:index], as: :log)

      resources("/token_transfers", TransactionTokenTransferController,
        only: [:index],
        as: :token_transfer
      )
    end

    resources("/accounts", AddressController, only: [:index])

    resources "/address", AddressController, only: [:show] do
      resources("/transactions", AddressTransactionController, only: [:index], as: :transaction)

      resources(
        "/internal_transactions",
        AddressInternalTransactionController,
        only: [:index],
        as: :internal_transaction
      )

      resources(
        "/validations",
        AddressValidationController,
        only: [:index],
        as: :validation
      )

      resources(
        "/contracts",
        AddressContractController,
        only: [:index],
        as: :contract
      )

      resources(
        "/contract_verifications",
        AddressContractVerificationController,
        only: [:new, :create],
        as: :verify_contract
      )

      resources(
        "/read_contract",
        AddressReadContractController,
        only: [:index, :show],
        as: :read_contract
      )

      resources("/tokens", AddressTokenController, only: [:index], as: :token) do
        resources(
          "/token_transfers",
          AddressTokenTransferController,
          only: [:index],
          as: :transfers
        )
      end

      resources(
        "/token_balances",
        AddressTokenBalanceController,
        only: [:index],
        as: :token_balance
      )

      resources(
        "/coin_balances",
        AddressCoinBalanceController,
        only: [:index],
        as: :coin_balance
      )

      resources(
        "/coin_balances/by_day",
        AddressCoinBalanceByDayController,
        only: [:index],
        as: :coin_balance_by_day
      )
    end

    resources "/tokens", Tokens.TokenController, only: [:show], as: :token do
      resources(
        "/token_transfers",
        Tokens.TransferController,
        only: [:index],
        as: :transfer
      )

      resources(
        "/read_contract",
        Tokens.ReadContractController,
        only: [:index],
        as: :read_contract
      )

      resources(
        "/token_holders",
        Tokens.HolderController,
        only: [:index],
        as: :holder
      )

      resources(
        "/inventory",
        Tokens.InventoryController,
        only: [:index],
        as: :inventory
      )
    end

    resources(
      "/smart_contracts",
      SmartContractController,
      only: [:index, :show],
      as: :smart_contract
    )

    get("/search", ChainController, :search)

    get("/chain_blocks", ChainController, :chain_blocks, as: :chain_blocks)

    get("/api_docs", APIDocsController, :index)
  end
end

apps/block_scout_web/lib/block_scout_web/controllers/chain/market_history_chart_controller.ex
defmodule BlockScoutWeb.Chain.MarketHistoryChartController do
  use BlockScoutWeb, :controller

  alias Explorer.{Chain, Market}
  alias Explorer.ExchangeRates.Token

  def show(conn, _params) do
    with true <- ajax?(conn) do
      exchange_rate = Market.get_exchange_rate(Explorer.coin()) || Token.null()

      market_history_data =
        30
        |> Market.fetch_recent_history()
        |> case do
          [today | the_rest] -> [%{today | closing_price: exchange_rate.usd_value} | the_rest]
          data -> data
        end
        |> encode_market_history_data()

      json(conn, %{
        history_data: market_history_data,
        supply_data: available_supply(Chain.supply_for_days(30), exchange_rate)
      })
    else
      _ -> unprocessable_entity(conn)
    end
  end

  defp available_supply(:ok, exchange_rate) do
    to_string(exchange_rate.available_supply || 0)
  end

  defp available_supply({:ok, supply_for_days}, _exchange_rate) do
    supply_for_days
    |> Jason.encode()
    |> case do
      {:ok, data} -> data
      _ -> []
    end
  end

  defp encode_market_history_data(market_history_data) do
    market_history_data
    |> Enum.map(fn day -> Map.take(day, [:closing_price, :date]) end)
    |> Jason.encode()
    |> case do
      {:ok, data} -> data
      _ -> []
    end
  end
end

apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex
defmodule BlockScoutWeb.ChainController do
  use BlockScoutWeb, :controller

  alias BlockScoutWeb.ChainView
  alias Explorer.{Chain, PagingOptions, Repo}
  alias Explorer.Chain.{Address, Block, Transaction}
  alias Explorer.Counters.AverageBlockTime
  alias Explorer.ExchangeRates.Token
  alias Explorer.Market
  alias Phoenix.View

  def show(conn, _params) do
    transaction_estimated_count = Chain.transaction_estimated_count()

    exchange_rate = Market.get_exchange_rate(Explorer.coin()) || Token.null()

    render(
      conn,
      "show.html",
      address_count: Chain.count_addresses_with_balance_from_cache(),
      average_block_time: AverageBlockTime.average_block_time(),
      exchange_rate: exchange_rate,
      chart_data_path: market_history_chart_path(conn, :show),
      transaction_estimated_count: transaction_estimated_count,
      transactions_path: recent_transactions_path(conn, :index)
    )
  end

  def search(conn, %{"q" => query}) do
    query
    |> String.trim()
    |> BlockScoutWeb.Chain.from_param()
    |> case do
      {:ok, item} ->
        redirect_search_results(conn, item)

      {:error, :not_found} ->
        not_found(conn)
    end
  end

  def chain_blocks(conn, _params) do
    if ajax?(conn) do
      blocks =
        [paging_options: %PagingOptions{page_size: 4}]
        |> Chain.list_blocks()
        |> Repo.preload([[miner: :names], :transactions, :rewards])
        |> Enum.map(fn block ->
          %{
            chain_block_html:
              View.render_to_string(
                ChainView,
                "_block.html",
                block: block
              ),
            block_number: block.number
          }
        end)

      json(conn, %{blocks: blocks})
    else
      unprocessable_entity(conn)
    end
  end

  defp redirect_search_results(conn, %Address{} = item) do
    redirect(conn, to: address_path(conn, :show, item))
  end

  defp redirect_search_results(conn, %Block{} = item) do
    redirect(conn, to: block_path(conn, :show, item))
  end

  defp redirect_search_results(conn, %Transaction{} = item) do
    redirect(
      conn,
      to:
        transaction_path(
          conn,
          :show,
          item
        )
    )
  end
end

apps/block_scout_web/lib/block_scout_web/views/chain_view.ex
defmodule BlockScoutWeb.ChainView do
  use BlockScoutWeb, :view

  alias BlockScoutWeb.LayoutView
end

apps/block_scout_web/lib/block_scout_web/templates/chain/_block.html.eex
<div class="col-lg-3 fade-up-blocks-chain" data-selector="chain-block" data-block-number="<%= @block.number %>">
  <div class="tile tile-type-block d-flex flex-column">
    <%= link(
          @block,
          class: "tile-title",
          to: block_path(BlockScoutWeb.Endpoint, :show, @block),
          "data-selector": "block-number"
        ) %>
    <div>
      <span class="mr-2"> <%= gettext("%{count} Transactions", count: Enum.count(@block.transactions)) %> </span>
      <span class="text-nowrap" data-from-now="<%= @block.timestamp %>"> </span>
    </div>
    <span class="text-truncate">
      <%= gettext "Miner" %>

      <%= render BlockScoutWeb.AddressView,
        "_link.html",
        address: @block.miner,
        contract: false %>
    </span>

    <%= if BlockScoutWeb.BlockView.show_reward?(@block.rewards) do %>
      <span class="text-truncate">
        <%= gettext "Reward" %>

        <%= BlockScoutWeb.BlockView.combined_rewards_value(@block) %>
      </span>
    <% end %>
  </div>
</div>

apps/block_scout_web/lib/block_scout_web/templates/chain/_metatags.html.eex
<title>
  <%= gettext("%{subnetwork} %{network} Explorer", subnetwork: LayoutView.subnetwork_title(), network: LayoutView.network_title()) %>
</title>
<meta name="description" content="<%= gettext "BlockScout provides analytics data, API, and Smart Contract tools for the %{subnetwork}", subnetwork: LayoutView.subnetwork_title() %>">
<meta name="keywords" content="BlockScout, blockchain, api, analytics, address, smart contract">

apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
<div class="dashboard-banner-container d-none d-md-block" data-page="chain-details">
  <img src="<%= static_path(@conn, "/images/cube.svg") %>" alt="cube_graphic" class="dashboard-banner-graphic">
  <div class="container">
    <div class="dashboard-banner">
      <div class="dashboard-banner-chart">
        <div data-chart-loading-message class="tile tile-muted text-center mt-5">
          <span class="loading-spinner-small mr-2">
            <span class="loading-spinner-block-1"></span>
            <span class="loading-spinner-block-2"></span>
          </span>
          <%= gettext("Loading chart") %>...
        </div>
        <button data-chart-error-message class="alert alert-danger col-12 text-left mt-5" style="display: none;">
          <span><%= gettext("There was a problem loading the chart.") %></span>
        </button>
        <canvas data-chart="marketHistoryChart" data-market_history_chart_path="<%= @chart_data_path %>" width="350" height="152" style="display: none;"></canvas>
      </div>
      <div class="dashboard-banner-chart-legend">
        <div class="dashboard-banner-chart-legend-item">
          <span class="dashboard-banner-chart-legend-label">
            <%= gettext "Price" %>
          </span>
          <span class="dashboard-banner-chart-legend-value" data-selector="exchange-rate" data-wei-value="<%= Explorer.Chain.Wei.from(Decimal.new(1), :ether).value %>" data-usd-exchange-rate="<%= @exchange_rate.usd_value %>">
          </span>
        </div>
        <div class="dashboard-banner-chart-legend-item">
          <span class="dashboard-banner-chart-legend-label">
            <%= gettext "Market Cap" %>
          </span>
          <span class="dashboard-banner-chart-legend-value" data-selector="market-cap" data-usd-value="<%= @exchange_rate.market_cap_usd %>">
          </span>
        </div>
      </div>
      <div class="dashboard-banner-network-stats">
        <%= case @average_block_time do %>
          <% {:error, :disabled} -> %>
            <%= nil %>
          <% average_block_time -> %>
            <div class="dashboard-banner-network-stats-item">
              <span class="dashboard-banner-network-stats-label">
                <%= gettext "Average block time" %>
              </span>
              <span class="dashboard-banner-network-stats-value" data-selector="average-block-time">
                <%= Timex.format_duration(average_block_time, Explorer.Counters.AverageBlockTimeDurationFormat) %>
              </span>
            </div>
        <% end %>
        <div class="dashboard-banner-network-stats-item">
          <span class="dashboard-banner-network-stats-label">
            <%= gettext "Total transactions" %>
          </span>
          <span class="dashboard-banner-network-stats-value" data-selector="transaction-count">
            <%= Cldr.Number.to_string!(@transaction_estimated_count, format: "#,###") %>
          </span>
        </div>
        <div class="dashboard-banner-network-stats-item">
          <span class="dashboard-banner-network-stats-label">
            <%= gettext "Wallet addresses" %>
          </span>
          <span class="dashboard-banner-network-stats-value" data-selector="address-count">
            <%= Cldr.Number.to_string!(@address_count, format: "#,###") %>
          </span>
        </div>
      </div>
    </div>
  </div>
</div>
<section class="container">
  <div class="card card-chain-blocks">
    <div class="card-body">
      <%= link(gettext("View All Blocks →"), to: block_path(BlockScoutWeb.Endpoint, :index), class: "button button-secondary button-xsmall float-right") %>
      <h2 class="card-title"><%= gettext "Blocks" %></h2>
      <div class="row" data-selector="chain-block-list" data-url="<%= chain_blocks_path(@conn, :chain_blocks) %>">
        <button data-selector="error-message" class="alert alert-danger col-12 text-left" style="display: none;">
          <span class="alert-link">
            <%= gettext "Something went wrong, click to reload." %>
          </span>
        </button>
        <div data-selector="loading-message" class="tile tile-muted text-center mt-3 w-100">
          <span class="loading-spinner-small mr-2">
            <span class="loading-spinner-block-1"></span>
            <span class="loading-spinner-block-2"></span>
          </span>
          <%= gettext("Loading...") %>
        </div>
      </div>
    </div>
  </div>

  <div class="card card-chain-transactions">
    <div class="card-body">
      <%= link(gettext("View All Transactions →"), to: transaction_path(BlockScoutWeb.Endpoint, :index), class: "button button-secondary button-xsmall float-right") %>
      <h2 class="card-title"><%= gettext "Transactions" %></h2>
      <div data-selector="channel-batching-message" style="display: none;">
        <div data-selector="reload-button" class="alert alert-info">
          <a href="#" class="alert-link"><span data-selector="channel-batching-count"></span> <%= gettext "More transactions have come in" %></a>
        </div>
      </div>
      <span data-selector="transactions-list" data-transactions-path="<%= @transactions_path %>">
        <button data-selector="error-message" class="alert alert-danger col-12 text-left" style="display: none;">
          <span class="alert-link">
            <%= gettext "Something went wrong, click to retry." %>
          </span>
        </button>
        <div data-selector="loading-message" class="tile tile-muted text-center mt-3">
          <span class="loading-spinner-small mr-2">
            <span class="loading-spinner-block-1"></span>
            <span class="loading-spinner-block-2"></span>
          </span>
          <%= gettext("Loading...") %>
        </div>
      </span>
    </div>
  </div>
</section>